<Project Sdk="Godot.NET.Sdk/4.4.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants Condition="Exists('lib\SimpleITK\SimpleITKCSharpManaged.dll')">$(DefineConstants);GVR_USE_SIMPLEITK</DefineConstants>
  </PropertyGroup>
  <ItemGroup Condition="Exists('lib\SimpleITK\SimpleITKCSharpManaged.dll')">
    <Reference Include="SimpleITKCSharpManaged">
      <HintPath>lib\SimpleITK\SimpleITKCSharpManaged.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="lib\SimpleITK\SimpleITKCSharpNative.dll" Condition="'$(OS)' == 'Windows_NT' And Exists('lib\SimpleITK\SimpleITKCSharpNative.dll')">
      <Link>SimpleITKCSharpNative.dll</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\SimpleITK\SimpleITKCSharpNative.so" Condition="'$(OS)' == 'Unix' And Exists('lib\SimpleITK\SimpleITKCSharpNative.so')">
      <Link>SimpleITKCSharpNative.so</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\SimpleITK\SimpleITKCSharpNative.dylib" Condition="'$(OS)' == 'OSX' And Exists('lib\SimpleITK\SimpleITKCSharpNative.dylib')">
      <Link>SimpleITKCSharpNative.dylib</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>